name: Crawl People Pages

on:
  schedule:
    # Run every 5 days at 3:00 AM UTC
    - cron: '0 3 */5 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  crawl-people:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Crawl All People Pages
        env:
          DEPLOYED_API_BASE_URL: ${{ secrets.DEPLOYED_API_BASE_URL }}
          INDEXER_KEY: ${{ secrets.INDEXER_KEY }}
        run: deno task seed crawl-people

      - name: Notify Success
        if: success()
        run: echo "✅ People crawler completed successfully"

      - name: Notify Failure
        if: failure()
        run: echo "❌ People crawler failed"
