name: Index Authors - Congress 11

on:
  schedule:
    # TODO: Temporary schedule for initial indexing - runs daily at 4:00UTC
    # Remove or adjust after initial data population is complete
    - cron: "0 4,16 * * *"
  workflow_dispatch: # Manual triggering

permissions:
  issues: write
  contents: read

jobs:
  index-authors-11:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Index Authors for Congress 11
        env:
          DEPLOYED_API_BASE_URL: ${{ secrets.DEPLOYED_API_BASE_URL }}
          INDEXER_KEY: ${{ secrets.INDEXER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: deno task seed index-authors 11

      - name: Notify Success
        if: success()
        run: echo "✅ Authors indexing for Congress 11 completed successfully"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Authors indexing for Congress 11 failed"
