name: Index Documents Information - Congress 16

on:
  # schedule:
  #   - cron: "0 9,21 * * *"
  workflow_dispatch: # Allow manual triggering

permissions:
  issues: write
  contents: read

jobs:
  index-documents-16:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Index Documents Information for Congress 16
        env:
          DEPLOYED_API_BASE_URL: ${{ secrets.DEPLOYED_API_BASE_URL }}
          INDEXER_KEY: ${{ secrets.INDEXER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: deno task seed index-documents-information 16

      - name: Notify Success
        if: success()
        run: echo "✅ Documents information indexing for Congress 16 completed successfully"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Documents information indexing for Congress 16 failed"
