name: Monthly Data Indexing

on:
  schedule:
    # Run on the 1st of every month at 2:00 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  index-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Monthly Indexing
        env:
          DEPLOYED_API_BASE_URL: ${{ secrets.DEPLOYED_API_BASE_URL }}
          INDEXER_KEY: ${{ secrets.INDEXER_KEY }}
        run: |
          deno task seed people-membership
          deno task seed people-information
          deno task seed committees-information

      - name: Notify Success
        if: success()
        run: echo "✅ Monthly indexing completed successfully"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Monthly indexing failed"
