name: Monthly Data Indexing

on:
  schedule:
    # Run on the 1st of every month at 2:00 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  index-data:
    runs-on: ubuntu-latest

    steps:
      - name: Index People Membership Data
        run: |
          curl -X POST ${{ secrets.API_BASE_URL }}/index/people/membership \
            -H "Content-Type: application/json" \
            -d '{"key": "${{ secrets.INDEXER_KEY }}"}'

      - name: Index People Information Data
        run: |
          curl -X POST ${{ secrets.API_BASE_URL }}/index/people/information \
            -H "Content-Type: application/json" \
            -d '{"key": "${{ secrets.INDEXER_KEY }}"}'

      - name: Index Committees Information Data
        run: |
          curl -X POST ${{ secrets.API_BASE_URL }}/index/committees/information \
            -H "Content-Type: application/json" \
            -d '{"key": "${{ secrets.INDEXER_KEY }}"}'

      - name: Notify Success
        if: success()
        run: echo "✅ Monthly indexing completed successfully"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Monthly indexing failed"
